### ISSUE TITLE
OAuth support broken in 0.29.2

### ISSUE THREAD

**Issue by dkliban** [pulp/pulp-cli#1093]
## Summary
I have configured pulp-cli to interact with Pulp on console.redhat.com which advertises OAuth as a security scheme. However, pulp-cli sends Basic auth instead of trying to get a Bearer token.

## Pulp and pulp-cli version info
pulpcore 3.61 and pulp-cli 0.29.2

## Additonal context
pulp-cli 0.28.4 works just fine.

**Comment by mdellweg** [comment]
Let me just cite the corresponding RFC:

"Clients in possession of a client password MAY use the HTTP Basic authentication scheme [...] The authorization server MUST support the HTTP Basic authentication scheme for authenticating clients [...]"

from: https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1
