### ISSUE TITLE
Make initial config file creation easier

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulp-cli#111]
Ok so the config file is already pretty easy to make:  https://github.com/pulp/pulp-cli#configuration It would be easier still though if the user didn't have to make the dir and then then the config file. If they could just have to edit it to customize it instead of the default that would be easier.

Does it make any sense to do any of the following?

a) have the config file created by default on installation.

b) have a CLI command that would populate the config file (kind of like pulp smash has).

What do you think?

**Comment by mdellweg** [comment]
I think, let's add a `pulp settings` or `pulp config` command that creates that file if necessary and uses https://click.palletsprojects.com/en/7.x/utils/#launching-applications to open it in their favourite editor.
