### ISSUE TITLE
Publish docs to http://docs.pulpproject.org/pulp_cli

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp-cli#127]
The ssh key secret is already set up (`PULP_DOCS_KEY`).

**Comment by mdellweg** [comment]
I see "some" docs published there, so does this mean "...automatically..., as part of the release process"?

**Comment by daviddavis** [comment]
Yea, we have [the automation in place](https://github.com/pulp/pulp-cli/blob/develop/.github/workflows/release.yml#L47-L56). If you agree, I think we can close this out.
