### ISSUE TITLE
Have json options accept json or a file

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp-cli#143]
Provide a generic way to have json options accept json or a file.

We did this for file repository modify: https://github.com/pulp/pulp-cli/blob/c1f1774661a80a156f82790ad5451902edcf772a/pulpcore/cli/file/repository.py#L175-L199

**Comment by mdellweg** [comment]
Does the change in #104 contain this feature?

**Comment by daviddavis** [comment]
Yes, it does. Closing this out.
