### ISSUE TITLE
Add support for autopublish and autodistribute

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp-cli#155]
https://pulp.plan.io/issues/7469

**Comment by dralley** [comment]
Support should be added for

* setting the "repository" field on distributions (all of them, after the new distribution models are rolled out)
* setting the "manifest" field on file repositories
* setting the "autopublish" field on file repositories

https://github.com/pulp/pulp_file/pull/492#issuecomment-815378823

* setting the "autopublish" field on rpm repositories
* setting the various publish options on rpm repositories, see https://github.com/pulp/pulp_rpm/pull/1938/files#diff-71a2808f74566cf951fcf9b0c3b895baaad58a568b4f26cc6f6ab22bef32d298R69-R103
