### ISSUE TITLE
Intuitive workflow for adding content to repositories

### ISSUE THREAD

**Issue by dralley** [pulp/pulp-cli#171]
The command ```repository add --name foo --filename "shelf-reader-0.1.tar.gz"``` is a little unintuitive, because you might think it's adding a repository, but it's adding content *to* a repository.

Would a reverse order work?  ```pulp python repository --foo add --filename "shelf-reader-0.1.tar.gz"```

Or maybe the names could be changed slightly?

```pulp python repository add-content --repo-name foo --filename "shelf-reader-0.1.tar.gz"```

**Comment by mdellweg** [comment]
The lookup option for name should be renamed to `--repository-name` to be in line with other nested subgroups. And the commands should be moved to a content subgroup.

`pulp python repository content add --repository-name foo --filename "shelf-reader-0.1.tar.gz"`
