### ISSUE TITLE
Add "rpm repo uploads erratum" to pulp-cli

### ISSUE THREAD

**Issue by lero** [pulp/pulp-cli#192]
Pulp 2 pulp-admin had the "rpm repo uploads erratum" functionality to upload erratas. Can we have the same for Pulp 3 in pulp-cli?

Thank you.

**Comment by mdellweg** [comment]
I believe this is implemented. https://github.com/pulp/pulp-cli/blob/main/tests/scripts/pulp_rpm/test_content.sh#L116

Keep in mind that errata are now called "Advisories".
