### ISSUE TITLE
Need some docs on how The Magic works for a command-author

### ISSUE THREAD

**Issue by ggainey** [pulp/pulp-cli#214]
We've done a lot to make writing commands declarative and with as little boiler-plate as possible. This is *great* - but it can make writing new commands/changing existing ones, challenging for someone new to the codebase. It would be great if there were a short overview doc on "How It All Works", for would-be command-writers.

**Comment by daviddavis** [comment]
This maybe has some overlap with https://github.com/pulp/pulp-cli/issues/96?

**Comment by ggainey** [comment]
Ugh, I failed to check first - closing this as a dup
