### ISSUE TITLE
Exception raised when supplying invalid json format

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp-cli#255]
When modifying a repository version, you get an exception message if the json format isn't a list of hashes.

Steps to reproduce:

```
pulp file repository create --name test2
pulp file repository content modify --repository test2 --add-content '{"sha256": "abc123", "relative_path": "test"}'
```

Exception:

```
TypeError: find() argument after ** must be a mapping, not str
```

**Comment by mdellweg** [comment]
I am marking this a bug only, because the documentation of this parameter is already rather explicit, but stacktraces are not suitable for users.

To solve it, should we just verify it's a list, or should we add a complete schema validation framework?

**Comment by daviddavis** [comment]
That's a good question and I don't have a strong preference.

**Comment by mdellweg** [comment]
We want to add some sort of validation in the cli at least.

**Comment by mdellweg** [comment]
https://pypi.org/project/schema/
looks promising
