### ISSUE TITLE
Support click 8

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp-cli#256]
Tasks:

- [ ] [click-shell](https://github.com/clarkperkins/click-shell) doesn't support click 8
~- [ ] get bash tab completion working~
- [ ] mypy linting is hard to impossible to fix for 7 and 8 simultaneously

edit: The shell completion issue is actually: https://github.com/pallets/click/issues/1940

**Comment by daviddavis** [comment]
Not sure if we can do anything about the last (mypy) bullet item?

**Comment by mdellweg** [comment]
To fix click shell, we intend to switch to https://github.com/gouttegd/click-shell
