### ISSUE TITLE
Validate when pulp-ansible and galaxy-ng are installed together

### ISSUE THREAD

**Issue by fao89** [pulp/pulp-cli#261]
Galaxy NG blocks pulp-ansible endpoints:
https://github.com/ansible/galaxy_ng/blob/master/galaxy_ng/app/webserver_snippets/nginx.conf

When Galaxy NG and Pulp Ansible are installed together, users will get 403 on pulp ansible calls.
This can confuse users with authentication errors, maybe we can add  some helpful error message like:
```
pulp-cli does not support galaxy_ng yet
```

**Comment by bmbouter** [comment]
+1 to an error message when galaxy_ng is installed and pulp_ansible is attempted to be used.

pulp-cli can't fix this though, is there a galaxy_ng issue tracking the removal of [this snippet](https://github.com/ansible/galaxy_ng/blob/master/galaxy_ng/app/webserver_snippets/nginx.conf#L14-L32)?

**Comment by mdellweg** [comment]
We may be able add a `PluginRequirement("galaxy_ng", max_version="0.0.0")` to the `pulp ansible` command group. But i am not sure if the resulting error message would serve your needs.

**Comment by mdellweg** [comment]
We should use `has_plugin` to issue this error message.
This might impact more endpoints, like users and groups.

**Comment by mdellweg** [comment]
I this still true?

**Comment by mdellweg** [comment]
I believe the api is exposed on a redirected path which pulp-cli supports.
