### ISSUE TITLE
As a user, I want to be able to deploy a global configuration file

### ISSUE THREAD

**Issue by evgeni** [pulp/pulp-cli#290]
Right now pulp-cli only reads `~/.config/pulp/settings.toml` (btw, why doesn't it mention *cli* enywhere?).

I would like to be able to deploy a `/etc/pulp/cli/settings.toml` (or whatever other path you can think of, in `/etc/pulp`) which will be loaded *before* the one in `~/.config`, so I can deploy "global" configuration defaults that vary from the ones in the app itself, but should be valid for all users.

Background: on Katello installations, I want to deploy pulp-cli with a default of `dry-run = true`.

**Comment by mdellweg** [comment]
Consider #293 also when refactoring configuration gathering.
