### ISSUE TITLE
Required plugin message is ambiguous

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp-cli#299]
Run a pulp_python command (e.g. `pulp python repository list`) without pulp_python installed. You'll get an error:

```
Error: The server does not have 'python>=3.1.0.dev' installed, which is needed to use this command.
```

This resulted in some confusion because the user thought that the CLI was telling them that their version of Python was outdated. The error should probably say `pulp_python` instead of `python`.

**Comment by mdellweg** [comment]
I agree that this is confusing. Even more so with pulp_python versions approaching 3.7 ...
If we do not want to carry the translation "app label" -> "python package" around, can we maybe reformulate to
"The server does not provide the component 'python>=3.1.0.dev', which is needed to use {this command}. See 'pulp status' for installed components."

Funny part: We used to report the package name in the status API...

**Comment by daviddavis** [comment]
Ah yea, I filed an issue here: https://pulp.plan.io/issues/9084

**Comment by daviddavis** [comment]
The error message looks good. I might be more specific though with "pulp component" or "plugin".
