### ISSUE TITLE
[RFE] Simplify pulp cli setup for connecting to satellite with parameters

### ISSUE THREAD

**Issue by latran** [pulp/pulp-cli#300]
Setup for pulp cli has mostly been manual whenever a user wants to connect to different satellites.  A user has to go to the `settings.toml` files, update the fields to include the new satellite name, then scp the `pulp-client.crt` and `pulp-client.key` in, and finally run `pulp status` to verify that it's connected successfully.  Can we automate that process with a parameter like `pulp --connect-sat <sat-name>` that would execute a script and filling all the needed info for the `settings.toml` file and pulling in the certs?  That would make things a lot easier when we're switching from satellite to satellite while using pulp-cli.

**Comment by mdellweg** [comment]
You can configure profiles and use them with the `--profile/-p` option. This may not yet been well documented however.

In short: add a `[cli-server1]` section to your `settings.toml` and run `pulp -p server1 status`.

**Comment by mdellweg** [comment]
We added docs for the profile option. #313 
However if you need other means of automatic setup (especially doing scp on certs) i'd see it as a separate tool.
If you already have a script, that collects all the necessary data, can't it just dump the certificates somewhere and fill the details in `~/.config/pulp/cli.toml` (formerly known as `settings.toml`)?

**Comment by evgeni** [comment]
We're handling the proper integration of pulp cli in the Katell installer in https://projects.theforeman.org/issues/34684

**Comment by mdellweg** [comment]
With all the taken measures mentioned above, I consider this issue closed.
Please reopen and comment on further improvements if you feel different.
