### ISSUE TITLE
`--limit 0` behavior differs from API

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp-cli#311]
Not sure if this is a problem but I noticed that `--limit 0` behaviors different than supplying limit=0 when hitting the api:

```
# returns all objects
$ http :/pulp/api/v3/repositories/file/file/ limit==0

$ pulp file repository list --limit 0
Not all -1 entries were shown.
[]
```

Also the message seems odd too (`Not all -1 entries were shown.`)

**Comment by mdellweg** [comment]
restrict to limits >=1
