### ISSUE TITLE
pulp-cli on centOS/RHEL 7?

### ISSUE THREAD

**Issue by mimmus** [pulp/pulp-cli#320]
Hi,
am I wrong or is it impossible to install pulp-cli on CentOS/RHEL 7 due to their deprecated python2.7?

**Comment by daviddavis** [comment]
I believe you should be able to install it if you have the `python3` package installed. Then run `pip3 install pulp-cli`.

**Comment by daviddavis** [comment]
The python3 package is in el7.

**Comment by mimmus** [comment]
Solved, thanks to a kind person on IRC!
pulp_installer installs python3 under /usr/local/lib/pulp/bin/python3.8.
You need to create a virtualenv for current user:
 `/usr/local/lib/pulp/bin/python3.8 -m venv pulp-cli`
activate it:
 `source pulp-cli/bin/activate`
and install locally to this virtualenv:
 `pip install pulp-cli`
