### ISSUE TITLE
Releases in the changelog are not titleized

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp-cli#337]
As an example:

```
0.11.0 (2021-08-10)

Features
--------

- Added support to specify skip-types on rpm sync.
  `#225 <https://github.com/pulp/pulp-cli/issues/225>`_
- Added lookup for a global config file ``/etc/pulp/cli.toml``.
  `#290 <https://github.com/pulp/pulp-cli/issues/290>`_
- ...
```

I think the 0.11.0 line should be a title.

**Comment by mdellweg** [comment]
Should we repurpose this issue to convert the CHANGELOG from rst to md?

**Comment by daviddavis** [comment]
That would be ideal 👍

**Comment by mdellweg** [comment]
For reference:
https://github.com/twisted/towncrier/issues/128

**Comment by daviddavis** [comment]
I'm hoping to work on this for docs day unless you'd prefer to work on it @mdellweg

**Comment by mdellweg** [comment]
Sorry, i started already.
