### ISSUE TITLE
pulp --version shows incorrect version

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp-cli#351]
It's like it's showing me the pulpcore version:

```
$ pip list | grep pulp-cli
pulp-cli                        0.12.0.dev0  /home/vagrant/devel/pulp-cli
$ pulp --version
pulp3 command line interface, version 3.16.0.dev0
```

**Comment by mdellweg** [comment]
I even get:
`RuntimeError: 'pulpcore' is not installed. Try passing 'package_name' instead.`
Seems like we need to redirect the click autodetect here.
