### ISSUE TITLE
Support "<...> content upload" and "<...> repository content add" in one go

### ISSUE THREAD

**Issue by thmo** [pulp/pulp-cli#385]
## Summary
Uploading RPMs and adding them to a repo currently needs two steps. It would be nice to have a command doing both in step (and optimally, even for multiple RPMs at once).

Current versions:
- pulp-cli 0.11.0-30-gc669815
- pulp-core 3.14.7
- pulp-rpm 3.14.5

## Examples
Currently needed:
```sh
file_href=$(pulp rpm content upload \
     --file "${file}" \
     --relative-path "$(basename "${file}")" |
		jq -r '.pulp_href')

pulp rpm repository content add \
     --repository "${repo}" \
     --package-href "${file_href}"
```
(assumed the repo has `autopublish` switched on).

Proposed cli command:
```sh
pulp rpm repository content publish \
    --repository "${repo}" \
    --file "${file}" \
    --relative-path "$(basename "${file}")"
```
Optionally one could support multiple `--file`, `--relative-path` options.

**Comment by thatsk** [comment]
is this any status on this

**Comment by mdellweg** [comment]
> is this any status on this

It's on the wishlist. I don't see anyone working on it ATM.
