### ISSUE TITLE
pulp rpm content: current implementation needs tweaking to support other rpm-content-types

### ISSUE THREAD

**Issue by ggainey** [pulp/pulp-cli#407]
## Summary

Instead of differentiating content-type by --type= , each content-type available to RPM needs to be its own command-group (ie, `rpm content package create` instead of `rpm content --type package create`

## Examples

Current implementation looks like `rpm content --type package create|list|show|upload` For create, upload, and list, arguments (esp required-arguments) are different for different content types. I think each content-type should be its own subcommand.

As an example. consider the following for 'create' calls for pulp-rpm content types ('r = 'required', '1' one-of required, '2' all-of-required if not set-1, 'o' = 'optional')

| Content | file | repo | artifact | rel_path | module | stream | profiles | NSVCA | [artifacts] | [deps] | [packages] |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | 
| advisory | r | o | | | | | | | | | |
| package | 1 | o | 1 | r | | | | | | | | 
| modulemd | 1 | o | 1 | r | | | | 2 | 2 | 2 | o | 
| modulemd_default | 1 | o | 1 | r | 2 | 2 | 2 | | |  |  | 

I propose to modify the existing `rpm content --type package` functionality to move it to its own subcommand `rpm content package create|upload|show|list` , under the aegis of this issue. Adding support for other rpm-content-types should happen under their own feature-requests, built on top of this proposal.

(Note: I should have thought of this when reviewing the initial package work; this is what happens when one focuses on a specific content-type during a review.

**Comment by mdellweg** [comment]
Can we close this?

**Comment by ggainey** [comment]
Replaced by #505, fixed in #506
