### ISSUE TITLE
Allow filtering tasks by the worker href

### ISSUE THREAD

**Issue by dralley** [pulp/pulp-cli#450]
e.g. `pulp task list --worker /pulp/api/v3/workers/6292f6e9-1f50-4597-bf6f-e64a2ef1ae4e/`

It's something you can do via the API, but the CLI doesn't support the option.  Support would like to be able to view the subset of tasks that have run on a particular worker easily.

**Comment by mdellweg** [comment]
I think this is notw a duplicate of #543
