### ISSUE TITLE
RPM sync ought to provide `sync_policy` option, mark `mirror` as deprecated

### ISSUE THREAD

**Issue by dralley** [pulp/pulp-cli#462]
The RPM plugin provides a `sync_policy` parameter to replace the `mirror` parameter and has marked the `mirror` parameter as deprecated.  The reason is that `mirror = bool` doesn't capture the full range of potentially desired behaviors, and is ambiguous when there could be multiple different meanings of "mirror".

The current choices for `sync_policy` are "additive", "mirror_content_only", and "mirror_complete"

https://github.com/pulp/pulp_rpm/pull/2146
https://docs.pulpproject.org/pulp_rpm/workflows/create_sync_publish.html#sync-repository-foo-using-remote-bar

**Comment by mdellweg** [comment]
Can you provide a breakdown of the plugin versions that introduce the new parameter and deprecate / remove the old one (if already applicable)?

**Comment by dralley** [comment]
It was introduced in pulp_rpm 3.16.0, but later backported to 3.14.9 at Katello's request.  It's not removed but it *is* mutually exclusive with `sync_policy` and will reject requests that supply both.

It's not present in 3.15 but we can consider that version effectively dead.  It has no downstream users and no z-releases.
