### ISSUE TITLE
Provide option aliases consistent across different subcommands

### ISSUE THREAD

**Issue by quba42** [pulp/pulp-cli#475]
## Summary
A sub-command about some entity (for example "repositories"), tends to refer to it's name using the option `--name`, while other sub-commands tend to refer to the same kind of entity via the entity name (e.g.: `--repository`)

This is inconvenient (particularly during ad hoc CLI usage), since I want to reuse the option I just typed when changing the sub-command. The idea, is to have option aliases (for backwards compatibility) that are descriptive irrespective of the subcommand (e.g.: `--repository-name`).

## Examples
Sticking with the above example see the difference between having to amend between the following two command pairs:
```
pulp deb repository show --name="test"
pulp deb repository version show --repository="test"
```
and
```
pulp deb repository show --repository-name="test"
pulp deb repository version show --repository-name="test"
```
In the latter case, I can simply add the subcommand, without needing to change the option.
Note that the example is `pulp deb`, but these particular subcommands are from common CLI and presumably used by every plugin.

## Things to consider/next steps
Before starting to code, it is necessary to identify a list of subcommands and options that could likewise benefit from a change like the one I have proposed for just one example. I am sure there are more than just the one.

## Extra Information
I originally formulated this issue as a discussion on discourse: https://discourse.pulpproject.org/t/pulp-cli-usability-discussion/370

**Comment by mdellweg** [comment]
Discussion here:
https://discourse.pulpproject.org/t/pulp-cli-usability-discussion/370/3
