### ISSUE TITLE
pulp-cli fails to start if a config file location is inaccessible (permissions)

### ISSUE THREAD

**Issue by zapp42** [pulp/pulp-cli#509]
## Summary
On freshly setup Pulp installation (using the official ansible installer), the /etc/pulp directory has mode
drwxr-x--- 3 root     pulp      4096 Jun  2 14:50 pulp

As /etc/pulp/cli.toml is the first location that is checked for the config file, this fails for all users besides root and pulp.

## Steps to reproduce
Try to use pulp-cli when the /etc/pulp directory is not readable for your user.

Maybe the fact that /etc/pulp is checked first is a problem on its own? Shouldn't this be a fallback, if no personal config file is found?

A fix is to not only catch FileNoFound exceptions but also PermissionExceptions when trying to load the config file.

**Comment by mdellweg** [comment]
> Maybe the fact that /etc/pulp is checked first is a problem on its own? Shouldn't this be a fallback, if no personal config file is found?

That is actually correct, since the configs are merged, the last one checked will win on any single value.

**Comment by zapp42** [comment]
Thank @mdellweg and sorry for not responding.  I have a lot going on at the moment.
