### ISSUE TITLE
Task history export

### ISSUE THREAD

**Issue by dralley** [pulp/pulp-cli#526]
## Summary

> 
> Pulp does not store pulp-task history in reasonably readable form. It is hard for support to provide RCA and sometimes troubleshoot pulp problems.  
> 
> Pulp3 uses pgsql now, so storing tasks at into some table can be very helpful.
> Export command like
> > 
> ```pulp tasks history export```

https://bugzilla.redhat.com/show_bug.cgi?id=2083490

**Comment by mdellweg** [comment]
How is this different from `pulp task list`?

**Comment by mdellweg** [comment]
Then i need more and better suggestions for the format.

**Comment by ggainey** [comment]
I responded to the originator in the BZ : https://bugzilla.redhat.com/show_bug.cgi?id=2083490#c1 Let's see what they respond with.

**Comment by mdellweg** [comment]
The bugzilla has been closed. There is no comment to be found for a better support from this end.
