### ISSUE TITLE
test_help_pages doesn't properly test polymorphic commands

### ISSUE THREAD

**Issue by gerrod3** [pulp/pulp-cli#580]
## Summary
`test_help_pages` iterates through all command groups and tests each commands help page, but it does not take into account that some commands are only callable from certain contexts when using the type option.

## Additonal context

Ideas:

Add an excludes list for certain commands to prevent them from being called without the proper context.

Add comments in the commands doc's string that the test checks to understand how or if the help page should be checked.

**Comment by lubosmj** [comment]
Another idea:

Set the proper context from within a test case (https://github.com/pulp/pulp-cli/blob/bd521c10adcca1d281cf42c883623e30ecd1b6b3/tests/test_help_pages.py#L13):
```
if instancecof(command.allowed_with_contexts, dict):
    for context in command.allowed_with_contexts.keys():
        yield args + ["-t", context]
```

This will require us to replace all affected occurrences of `allowed_with_contexts=(PulpEntityContext,)` by `allowed_with_contexts={"name": PulpEntityContext}`.
