### ISSUE TITLE
Refactor distribution-create-options

### ISSUE THREAD

**Issue by ggainey** [pulp/pulp-cli#592]
## Summary
Create-distribution-foo comes with a set of parameters from puplcore, some of which are required. Currently, every plugin has to define all the create-options "on their own", resulting in a lot of very similar code.

Let's refactor to get the common code into the core class, so plugins only have to add their plugin-specific choices (if any)

**Comment by mdellweg** [comment]
Feels like this is done already. Please reopen if you think otherwise.
