### ISSUE TITLE
Add support for repositories/reclaim_space 

### ISSUE THREAD

**Issue by ggainey** [pulp/pulp-cli#620]
## Summary
Add support for this REST call :+1: 
https://docs.pulpproject.org/pulpcore/workflows/reclaim-disk-space.html

**Comment by MichalPysik** [comment]
I'm currently working on this issue, but there is a little thing that could use a quick discussion. The call needs a list of repositories which should be used, and also list of hrefs of versions to ignore. I'm currently passing both parameters as lists, but they can also be individual duplicate command line parameters (```./program --repo "repo1" --repo "repo2" --repo repo3```). What do you think?

**Comment by MichalPysik** [comment]
I've discussed with @lubosmj quite a lot, and so far settled on the idea (which can be changed if someone disagrees) of using ```{--repo one --repo two | --all} --ignored_versions [href1_, ..., href_n], meaning that one can list individual repositories (or use --all), but list is still used for the optional repository versions to ignore.

**Comment by lubosmj** [comment]
@evgeni, some commands allow the following:
```
# a list of hrefs
tests/scripts/pulpcore/test_orphans.sh:    expect_succ pulp orphan cleanup --content-hrefs "[\"$content_href\"]"
```
or
```
# a list of key-value pairs
tests/scripts/pulp_file/test_content_bulk.sh:expect_succ pulp file repository modify --repository "cli_test_file_repository" --remove-content "[{\"sha256\":\"$sha256_1\",\"relative_path\":\"upload_test/test_1.txt\"},{\"sha256\":\"$sha256_2\",\"relative_path\":\"upload_test/test_2.txt\"},{\"sha256\":\"$sha256_3\",\"relative_path\":\"upload_test/test_3.txt\"}]"
```

So, another option was to list repositories in this fashion:
```
pulp repository reclaim --repos "[\"aa\", \"bb\"]"
```

I do not like it though. Being consistent does not always mean being proper. We can later focus on improving and unifying the interface of commands that accept a list of string values in the `"[\"$\"]"` format.

I am leaning more towards what @MichalPysik has proposed in the comment above,

**Comment by lubosmj** [comment]
Another option for `--ignored_versions` is to allow passing pairs of `--repo-name/version-number`. Users will not need to manually extract the hrefs of versions themselves. This can be studied later.
