### ISSUE TITLE
Can we provide pulp-cli as RPMs in Fedora?

### ISSUE THREAD

**Issue by ggainey** [pulp/pulp-cli#627]
## Summary
The folks who run COPR are investigating Pulp, and it would help if pulp-cli was an "official" Fedora package. Can we make this happen?

praiskup has done an experiment, it looks like it might be an easy win:

https://copr.fedorainfracloud.org/coprs/praiskup/pulp-cli/monitor/

- [x] Own pulp-cli building in COPR
- [x] #1084
- [x] Go through the package-maintainers acceptance process to become official Fedora package-maintainers

**Comment by mdellweg** [comment]
https://docs.fedoraproject.org/en-US/package-maintainers/New_Package_Process_for_New_Contributors/

**Comment by mdellweg** [comment]
pulp-glue is packaged and shipped:
https://bugzilla.redhat.com/show_bug.cgi?id=2313205

**Comment by mdellweg** [comment]
And pulp-cli too:
https://bugzilla.redhat.com/show_bug.cgi?id=2313276
