### ISSUE TITLE
broken reference to pulp-glue in main branch

### ISSUE THREAD

**Issue by maciej-markowski** [pulp/pulp-cli#654]
## Summary
Reference to pulp-glue was recently bumped which breaks the installation.

## Steps to reproduce
```
(venv) [vagrant@nmdws ~]$ git clone --depth=1 https://github.com/pulp/pulp-cli.git
Cloning into 'pulp-cli'...
remote: Enumerating objects: 288, done.
remote: Counting objects: 100% (288/288), done.
remote: Compressing objects: 100% (229/229), done.
remote: Total 288 (delta 74), reused 165 (delta 42), pack-reused 0
Receiving objects: 100% (288/288), 247.33 KiB | 2.78 MiB/s, done.
Resolving deltas: 100% (74/74), done.
(venv) [vagrant@nmdws ~]$ cd pulp-cli
(venv) [vagrant@nmdws pulp-cli]$ pip install .
Processing /home/vagrant/pulp-cli
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting click<9.0.0,>=8.0.0
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
ERROR: Could not find a version that satisfies the requirement pulp-glue==0.19.0.dev (from pulp-cli==0.19.0.dev0) (from versions: 0.0.0, 0.17.0, 0.17.1, 0.18.0)
ERROR: No matching distribution found for pulp-glue==0.19.0.dev (from pulp-cli==0.19.0.dev0)
```

## Expected behavior
Installation is completed correctly.

## Stacktrace/Error log
ERROR: Could not find a version that satisfies the requirement pulp-glue==0.19.0.dev (from pulp-cli==0.19.0.dev0) (from versions: 0.0.0, 0.17.0, 0.17.1, 0.18.0)
ERROR: No matching distribution found for pulp-glue==0.19.0.dev (from pulp-cli==0.19.0.dev0)

## Additonal context
pulp-cli installation from main branch is used in pulp_python pipeline and this bumped reference causes pipeline to fail.
https://github.com/maciej-markowski/pulp_python/actions/runs/4417009990/jobs/7744404558#step:6:257

**Comment by mdellweg** [comment]
This is a source installation. It needs to install the cli and glue in the same call to the same version.
`pip install ./pulp-cli ./pulp-cli/pulp-glue` should work.

`pip install -e ./pulp-cli -e ./pulp-cli/pulp-glue` for editable installations.

**Comment by mdellweg** [comment]
I figured, this information is misleading in the docs. Will fix it.
