### ISSUE TITLE
"pulp rpm content list" only shows packages - there's no way to view other content types

### ISSUE THREAD

**Issue by dralley** [pulp/pulp-cli#664]
## Summary

There's no options available for viewing other  content types such as modules or packagegroups.  Even if we don't support these types immediately, we should go ahead and restructure the API so that it is possible in the future.  It's unfortunate that we will likely need to break the currage usage to accomplish this, but it would be better to rip the bandage off sooner rather than later.

What we want is something more like `pulp rpm content package list`

**Comment by ggainey** [comment]
"package" is just the default if you don't specify a `--type` : 
```
 $ pulp rpm content --help
Usage: pulp rpm content [OPTIONS] COMMAND [ARGS]...

Options:
  -t, --type [package|advisory|distribution_tree|modulemd_defaults|modulemd|package_category|package_environment|package_group|package_langpack|repo_metadata_file]
  --help                          Show this message and exit.

Commands:
  create
  list
  show
  upload
```
