### ISSUE TITLE
Weird documentation URLs

### ISSUE THREAD

**Issue by quba42** [pulp/pulp-cli#709]
Not sure how important this is, but I noticed the [pulp-cli documentation](https://docs.pulpproject.org/pulp_cli/) uses some rather odd URLs relative to every other component documentation I have checked.

For example, every plugin I checked as well as core has:
```
https://docs.pulpproject.org/pulpcore/changes.html
```
But for pulp_cli it's:
```
https://docs.pulpproject.org/pulp_cli/CHANGES/
```

Similar for other documentation sections. Is there a reason for this? Are we building the docs for pulp-cli differently somehow?

### Expectation:

Keeping documentation URLs consistent across different plugins for easy navigation.

**Comment by mdellweg** [comment]
The docs in the cli are written in markdown using mkdocs instead of ReST and sphinx.
I think this brings that change along.
