### ISSUE TITLE
Using -b with async ansible commands errors or gives incorrect results

### ISSUE THREAD

**Issue by gerrod3** [pulp/pulp-cli#85]
The '-b' or '--background' option runs commands without waiting for any tasks generated by the commands to complete. Some of the async ansible commands show the results of the tasks expecting them to be finished.  Using the '-b' option skips the waiting causing them to error or show an incorrect result. The commands currently affected are:

- distribution create & update
- remote update
- repository update

Solution:
Use the passed pulp_context to check if the '-b' option is set and then appropriately show the results of the task or not.

**Comment by mdellweg** [comment]
I believe we found a deeper problem in the design how we handle tasks here. Maybe, with `background=True`, the task loop should exit in the same way as hitting ctrl-c, with an exception.
