### ISSUE TITLE
`pipx install pulp-cli[pygments]` does not correctly install setuptools on Python 3.12

### ISSUE THREAD

**Issue by JeppeKlitgaard** [pulp/pulp-cli#865]
## Summary
On an Ubuntu 22.04 server, installation via `pipx` does not work out of the box

## Steps to reproduce

1. `pipx install pulp-cli[pygments]`
2. `pulp`

Gives

```
Traceback (most recent call last):
  File "/home/jkl/.local/bin/pulp", line 5, in <module>
    from pulp_cli import main
  File "/home/jkl/.local/share/pipx/venvs/pulp-cli/lib/python3.12/site-packages/pulp_cli/__init__.py", line 5, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

## Expected behavior
For `pulp-cli` to run

## Pulp and pulp-cli version info

- `pulp3 command line interface, version 0.22.0`

## Fix

This can be manually fixed by issuing:

```
pipx inject pulp-cli[pygments] setuptools
```

**Comment by mdellweg** [comment]
On a first attempt I could not reproduce this on a debian machine. Probably I have the setuptools package installed globally.

**Comment by JeppeKlitgaard** [comment]
> On a first attempt I could not reproduce this on a debian machine. Probably I have the setuptools package installed globally.

I reckon you're right that `python3-setuptools` being installed may fix this. I think you've already managed to fix this (thank you for the rather incredible turn-around time on that!). I am happy to try and reproduce this in a Dockerfile if you think that would be helpful

**Comment by mdellweg** [comment]
> > On a first attempt I could not reproduce this on a debian machine. Probably I have the setuptools package installed globally.
> 
> I reckon you're right that `python3-setuptools` being installed may fix this. I think you've already managed to fix this (thank you for the rather incredible turn-around time on that!). I am happy to try and reproduce this in a Dockerfile if you think that would be helpful

I'd love to hear you confirming that this approach works. It turned out that using `pkg_resources` was deprecated after all.
