### ISSUE TITLE
Support `pip install pulp-cli[all]`

### ISSUE THREAD

**Issue by dkliban** [pulp/pulp-cli#878]
It would be nice if you could install pulp-cli and all the known plugin extensions by running 

`pip install pulp-cli[all]`

This would install `pulp-cli`, `pulp-cli-deb`, `pulp-cli-maven`, `pulp-cli-ostree`, `pulp-cli-gem`.

**Comment by mdellweg** [comment]
I sense that it is kind of hard to know at any given time what "all" plugins are.
The moment we release a new version on pulp-cli, no plugin may even be compatible with that. And the dependeny is clearly "plugin depends on core". As long as pythons "optional dependencies" are a kind of dependency, i fear this will only generate friction.
