### ISSUE TITLE
Auto-deletion of specific artifacts after a retention period

### ISSUE THREAD

**Issue by swetha-swaminathan1** [pulp/pulp-cli#891]
## Summary

I am currently maintaining multiple versions of certain component in my pulp repository and it looks something like this -
![image](https://github.com/pulp/pulp-cli/assets/133217791/edc7896d-556e-4542-aa50-b0aec600bb5d)

Lets say that i want have maximum of 4 versions of the component in pulp. Then, once v5 comes into the repository, v1 must automatically get deleted. Currently I don't see any command to enable any auto-delete feature or retention feature for an artifact. My only solution right now is to manually run delete command -
pulp file repository content modify --remove-content TEXT
i dont want to have to run the modify/delete command everytime a new version comes in, it would be great if there is a command that lets you enable some sort of automatic delete feature.
This there any way to already do this? Or is this a new feature that needs to be implemented?

**Comment by mdellweg** [comment]
Let's dissect this a little:
1. We use the term "artifact" in pulp for any stored binary object. At this level of abstraction it should be considered internal plumbing.
2. You seem to be handling file content. A piece of file content is a specific artifact with a certain relative path.
3. File content does not have any notion of a version, like deb or rpm packages. So it'd be impossible to "keep the 3 last versions of all files".
4. File content is stored in file repositories and as all repositories in pulp, they are versioned. So in fact, a piece of file content is in one or more repository versions. And repositories have a version retention feature.
5. Repository versions can be independently published and served.

 I can only assume, "V1", "V2" ... are path prefixes of content in your file repository. And each path contains a set of files ought to be versioned unisono. So it strikes me that you may want to have the content of "V1" in the first version of a repository, "v2" in the second, and so on. Set the version retention to 4 and server the resulting versions by distributions with corresponding base_paths "V1", "v2", ...
Some automation around this is probably still needed.

**Comment by swetha-swaminathan1** [comment]
Yes, v1, v2.. etc are path prefixes inside which the artifacts associated with that particular version is stored. 
> So it strikes me that you may want to have the content of "V1" in the first version of a repository, "v2" in the second, and so on. Set the version retention to 4 and server the resulting versions by distributions with corresponding base_paths "V1", "v2", ...

Regarding this, i would have contents of v1 in the first version of repository, but i will also have it in the subsequent versions of the repository. So i would have to cleanup the contents of the repository everytime before i sync the contents of a new version right? So v1 would be in the first repository version, v3 would be in the third repository version and so on..
Is there any other way to do this or is this the only way this can be done?

**Comment by mdellweg** [comment]
> To solve this problem i thought of an approach. I would have to cleanup the contents of the repository everytime before i sync the contents of a new version right? So v1 would be in the first repository version, v3 would be in the third repository version and so on. This way when v1 goes out, pulp orphan cleanup will remove the v1 contents from pulp. Is there any other way to do this or is this the only way this can be done?

This sounds like a mirrored sync (there the mirror flag when synching). It adjusts added and removed content so that the new version represents only what was found upstream.
When you use modify to create a new repository version, you would need to calculate the add and remove parts outside of pulp for the moment.

**Comment by mdellweg** [comment]
In any case, this is not a pulp CLI issue, but a question of how to draft a workflow. Please resort to the documentation.

**Comment by swetha-swaminathan1** [comment]
oh, wow I didn't realize this flag existed. This makes my problem easier. meanwhile I was also wondering if there is an option to selectively sync only certain artifacts inside a pulp manifest without syncing everything inside it?
