### ISSUE TITLE
config command stopped working after 41538e6

### ISSUE THREAD

**Issue by decko** [pulp/pulp-cli#928]
## Summary
After updating pulp-cli and pulp-glue to the latest version of `main` branch, the config command keeps complaining about the `base_url` field.

## Steps to reproduce

Running the command:
```
pulp config create --username admin --password password --base-url http://localhost:5001/pulp/api/v3/
```

always return the following prompt:
```
Config file failed to parse. ('base_url' should be of the form '<schema>://<netloc>').
Continue without config? [y/N]:
```

## Expected behavior

It should run without issues and create or update the config file.

## Pulp and pulp-cli version info

Only happens after 41538e6. 8437376 and before is not affected by this.

**Comment by mdellweg** [comment]
And it's rightfully complaining. "/pulp/api/v3" is not part of the `base_url`. At best "/pulp/" is supposed to be the `api_root`.
I forgot why we keep them separate, but that's the way it is.
In any case your example never worked.

**Comment by mdellweg** [comment]
I remember now pulp_cli predates both the api-root and the domains feature so the semantics of base_url were already defined back then in the most convenient way. And for users of unrerouted pulp installations it is still convenient.
