### ISSUE TITLE
As a user, I can download and verify content

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp-cli#94]
In Pulp 2, there was a command to do this (`pulp-admin repo download --repo-id <repo_id> --verify-all`). Support has asked for this in Pulp 3.

**Comment by mdellweg** [comment]
Is this the same as setting the DL-policy to immediate and issue a sync?

**Comment by daviddavis** [comment]
I had to dig into Pulp 2 to find out but here's [the download command code in Pulp 2](https://github.com/pulp/pulp/blob/9c0fb3893b97da328af9ca59575763ed363c38d2/client_lib/pulp/client/commands/repo/sync_publish.py#L363) and some [docs for verify_all_units on download](https://docs.pulpproject.org/en/2.21/dev-guide/integration/rest-api/repo/sync.html#download-a-repository). I believe this functionality exists in Pulp 3 today (albeit not as a single command).

I'm checking with support to see if we need a specific command for this functionality.

**Comment by daviddavis** [comment]
I've given this some more thought and I think that having a way to download content for a repo version would be ideal. I filed an issue against pulp. Feedback is welcome.

https://pulp.plan.io/issues/7986

**Comment by mdellweg** [comment]
I don't see any movement on https://github.com/pulp/pulpcore/issues/1976.
So i'm closing it here. Feel free to reopen once the pulpcore feature exists.
